### ISSUE TITLE
Nicistore not installing

### ISSUE THREAD

**Issue by tintutech** [yoonic/nicistore#31]
Hi ,

I'm facing some issues while installing "npm install"

_**WARN invalid config loglevel="notice"
Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.2/darwin-x64-57_binding.node": HTTP error 404 Not Found

> node-sass@3.3.2 postinstall /Applications/MAMP/htdocs/nicistore/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Applications/MAMP/htdocs/nicistore/node_modules/pangyp/bin/node-gyp.js rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Applications/MAMP/htdocs/nicistore/node_modules/pangyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using pangyp@2.3.3
gyp info using node@8.11.2 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /Users/tintu/anaconda3/bin/python
gyp verb check python version `python -c "import platform; print(platform.python_version());"` returned: "3.6.3\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "python" is v3.6.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/MAMP/htdocs/nicistore/node_modules/pangyp/lib/configure.js:110:14)
gyp ERR! stack     at /Applications/MAMP/htdocs/nicistore/node_modules/pangyp/lib/configure.js:99:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/Applications/MAMP/htdocs/nicistore/node_modules/pangyp/bin/node-gyp.js" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Applications/MAMP/htdocs/nicistore/node_modules/node-sass
gyp ERR! node -v v8.11.2
gyp ERR! pangyp -v v2.3.3
gyp ERR! not ok**_ 

npm => 5.6.0
node => v8.11.2

MAC OX

**Comment by lery12** [comment]
I have the same issue!

**Comment by lery12** [comment]
Edit package.json to install node-sass 4.9.0
